services:
  sibas:
    build:
      context: .
      dockerfile: Dockerfile
    image: sibas:latest
    container_name: sibas-container
    ports:
      - "8080:3000"
    env_file:
      - .env
    restart: unless-stopped
